"""
Synthetic Input Detection Rules
================================

Author:
    Jonatan "Johnny" Rassekhnia (@J-01R)

Role:
    Cybersecurity & Information Security Researcher

Project:
    Defensive Keylogger Analysis Lab

Description:
    Provides explainable detection rules for identifying synthetic
    keyboard-like telemetry generated by the laboratory's test
    environment.

Security Scope:
    These rules analyze previously generated synthetic telemetry.
    They do not monitor the keyboard, capture user input, inspect
    application contents, or perform system-wide input collection.

Copyright:
    Copyright (c) 2026 Jonatan "Johnny" Rassekhnia
    All Rights Reserved.

License:
    This project is not released under an open-source license.
    See the repository LICENSE file for usage restrictions.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path


RULES = {
    "SYNTHETIC_INPUT_ACTIVITY": {
        "severity": "HIGH",
        "description": (
            "A process generated synthetic keyboard-like telemetry."
        ),
    },
    "UNEXPECTED_INPUT_VOLUME": {
        "severity": "MEDIUM",
        "description": (
            "A process generated more synthetic input events "
            "than the configured threshold."
        ),
    },
}


def load_events(path: Path) -> list[dict]:
    """Load synthetic telemetry records from a JSONL file.

    Args:
        path: Path to the synthetic telemetry JSONL file.

    Returns:
        A list of decoded telemetry events.
    """
    with path.open(encoding="utf-8") as handle:
        return [
            json.loads(line)
            for line in handle
            if line.strip()
        ]


def detect(
    events: list[dict],
    volume_threshold: int = 10,
) -> list[dict]:
    """Apply explainable detection rules to synthetic telemetry.

    Args:
        events: Synthetic telemetry events to analyze.
        volume_threshold: Number of events required to trigger the
            input-volume rule.

    Returns:
        A list of detection findings containing the rule identifier,
        severity, affected process, evidence count, and rationale.

    Notes:
        These rules are intentionally limited to the synthetic
        laboratory telemetry format. They are not intended to
        determine malicious activity on their own.
    """
    findings = []

    synthetic = [
        event
        for event in events
        if event.get("synthetic") is True
    ]

    if synthetic:
        processes = Counter(
            event.get("process_name", "unknown")
            for event in synthetic
        )

        for process, count in processes.items():
            findings.append(
                {
                    "rule_id": "SYNTHETIC_INPUT_ACTIVITY",
                    "severity": RULES[
                        "SYNTHETIC_INPUT_ACTIVITY"
                    ]["severity"],
                    "process": process,
                    "evidence_count": count,
                    "rationale": RULES[
                        "SYNTHETIC_INPUT_ACTIVITY"
                    ]["description"],
                }
            )

            if count > volume_threshold:
                findings.append(
                    {
                        "rule_id": "UNEXPECTED_INPUT_VOLUME",
                        "severity": RULES[
                            "UNEXPECTED_INPUT_VOLUME"
                        ]["severity"],
                        "process": process,
                        "evidence_count": count,
                        "rationale": RULES[
                            "UNEXPECTED_INPUT_VOLUME"
                        ]["description"],
                    }
                )

    return findings


def main() -> None:
    """Run detection rules against synthetic telemetry."""
    parser = argparse.ArgumentParser(
        description=(
            "Analyze synthetic input telemetry using "
            "explainable detection rules."
        )
    )

    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/synthetic_events.jsonl"),
        help="Input JSONL telemetry file.",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=Path("reports/detections.json"),
        help="Output JSON detection report.",
    )

    parser.add_argument(
        "--threshold",
        type=int,
        default=10,
        help="Synthetic input-volume threshold.",
    )

    args = parser.parse_args()

    findings = detect(
        load_events(args.input),
        args.threshold,
    )

    args.output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    args.output.write_text(
        json.dumps(findings, indent=2),
        encoding="utf-8",
    )

    for finding in findings:
        print(
            f"[{finding['severity']}] "
            f"{finding['rule_id']} "
            f"process={finding['process']} "
            f"evidence={finding['evidence_count']}"
        )


if __name__ == "__main__":
    main()